replace autoremove with purge-old-kernels

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,8 +5,7 @@ set -e
 case "$1" in
     configure)
         
-	chmod +x /usr/bin/sostat*
-	chmod +x /usr/bin/soup
+	chmod +x /usr/bin/sostat* /usr/bin/soup /usr/bin/so-purge-old-kernels || echo "Unable to set sostat utilities executable."
 	
 	FILE="/etc/update-manager/release-upgrades"
 	if [ -f $FILE ]; then
