soup: work around Docker change Security-Onion-Solutions/security-onion#1804

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,7 +5,7 @@ set -e
 case "$1" in
     configure)
         
-	chmod +x /usr/sbin/so-apt-check /usr/sbin/sostat* /usr/sbin/soup /usr/sbin/so-purge-old-kernels || echo "Unable to set sostat utilities executable."
+	chmod +x /usr/sbin/so-apt-check /usr/sbin/so-docker-fix /usr/sbin/sostat* /usr/sbin/soup /usr/sbin/so-purge-old-kernels || echo "Unable to set sostat utilities executable."
 	
 	FILE="/etc/update-manager/release-upgrades"
 	if [ -f $FILE ]; then
@@ -50,6 +50,9 @@ case "$1" in
 		echo "We recommend removing the docker-ce and docker-ce-cli packages and re-installing:"
 		echo "sudo apt purge docker-ce docker-ce-cli && sudo apt install docker-ce docker-ce-cli"
 	fi
+
+	# Emergency fix for Docker service
+	/usr/sbin/so-docker-fix || echo "Unable to fix Docker service!"
 
     ;;
 
