securityonion-sostat: re-apply debconf noninteractive setting so that soup can proceed unattended Security-Onion-Solutions/security-onion#1523

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -34,6 +34,11 @@ case "$1" in
 		fi
 	fi
 
+	# If new debconf package installs, it may reset our noninteractive setting.
+	# This may result in things like wireshark prompting the user about dumpcap privs.
+	# Re-apply the noninteractive setting so that soup can proceed unattended.
+	echo "debconf debconf/frontend select noninteractive" | debconf-set-selections || echo "Unable to set debconf to noninteractive!"
+
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
